### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by nipunn1313** [06chaynes/http-cache#12]
Hi, would love a changelog on the project, so we know what changes between versions - especially the more major releases (eg 0.3 -> 0.4)

Thanks!

**Comment by 06chaynes** [comment]
Totally agree

Things were rapidly changing and there were more unknowns as to implementation at the beginning so I didn't really bother with it. Now that things have (more or less) stabilized I'll try to keep a log of at least any major changes going forward.

**Comment by 06chaynes** [comment]
I went ahead and added a separate changelog for each of the three crates, and added a sym link to the core library changelog to the root of the workspace. Now all I need to do is remember to add meaningful updates to them!
