### ISSUE TITLE
`CACacheManager.path` should be a `PathBuf`, not a `String`

### ISSUE THREAD

**Issue by iliana** [06chaynes/http-cache#24]
https://github.com/06chaynes/http-cache/blob/20bbf6eb7ae3846cfe8dc148f22bb6292cb894b6/http-cache/src/managers/cacache.rs#L10-L13

cacache's methods accept anything that implements `AsRef<Path>`, and if you already have a `PathBuf` (say from [dirs](https://docs.rs/dirs/5.0.1/dirs/index.html)) it is harder to get a `String`. (But it is easy to go from a String to a PathBuf via `PathBuf::from`.)

**Comment by 06chaynes** [comment]
This change has been merged in, thanks again!
