### ISSUE TITLE
Option to force cache regardless of Cache-Control headers?

### ISSUE THREAD

**Issue by alxpettit** [06chaynes/http-cache#27]
I tried setting `mode` to ForceCache, and playing around with `options -- to no avail. Is this simply not implemented?

**Comment by 06chaynes** [comment]
ForceCache should return the object from cache should it exists, ignoring staleness, but return a network error should the object not exist. 

What is the behavior you are experiencing?

**Comment by 06chaynes** [comment]
After checking more into this I did find I needed to adjust the test for the ForceCache mode to make sure the cached object would be stale upon retrieval from cache (https://github.com/06chaynes/http-cache/commit/994cd41ebd67cf82ea3064809b9ffe2514389760), the test did pass though so things should be working as expected for that mode.

**Comment by cchance27** [comment]
i believe what he's looking for is a way to ignore the cache headers and just always cache the result of a request for a duration....  basically 

```let is_cacheable = middleware.is_method_get_head()
            && self.mode != CacheMode::NoStore
            && self.mode != CacheMode::Reload;``` 

an escape hash for this like  

```let is_cacheable = self.mode == CacheMode::AlwaysCache || (middleware.is_method_get_head()
            && self.mode != CacheMode::NoStore
            && self.mode != CacheMode::Reload);```

which i don't think is possible currently?

**Comment by alxpettit** [comment]
@cchance27 

She/her please, but yes, I recall having trouble with this. For the project I was working on, I ended up refactoring to use my own crude content-addressable cache logic in that project, but I can probably still dig up the experimental branch if need be.

**Comment by cchance27** [comment]
@alxpettit sorry fixed :) Would have been cool to PR that in, if this projects accepting PRs or is active still. As I can definitely see the usefulness of an option like that, for instance i call out to an API and the http-cache tags are irrelevant to me as I don't really need more than 1 update per 24 hours, so being able to just say set my own TTL as an override, would be so much better.

**Comment by 06chaynes** [comment]
It's something I can look into on my free time (if that ever becomes a thing again), but I absolutely would be happy to consider any PRs to the project.

**Comment by 06chaynes** [comment]
Welcoming any thoughts on what I've worked out so far on this matter. I have a branch with the changes made here if interested https://github.com/06chaynes/http-cache/blob/ignore-rules/http-cache/src/lib.rs#L294

Right now this adds a new variant to `CacheMode` called `IgnoreRules`. This should ignore the the checks that determine if a response can be cached (other than being a 200 status) and the check that determine staleness. This will assume that you are managing the expiry of the cache record somewhere else (such as the options for the cache manager you are using if provided or by interfacing with the cache in a more direct manner).

**Comment by 06chaynes** [comment]
@cchance27 @alxpettit forgot to tag, curious if you have any input on this new mode before merging to develop.

**Comment by cchance27** [comment]
Sorry been bit busy with work, a cursory look I think it meets what I was expect originally to be supported, leaving the TTL to the backend for the storage makes sense i think, i'll try to find time to play with it but i don't see any reason it shouldn't be mergeable as doesn't appear to break any of the original workflows you were originally handling, and does give us that option to override the is_cacheable checking on 200 returns, which is great.

**Comment by alxpettit** [comment]
@06chaynes Seems reasonable :)

**Comment by 06chaynes** [comment]
Just merged this change into develop, it'll be part of the next release once I have a chance to finish a few other changes up. Thanks again!

**Comment by alxpettit** [comment]
Thanks for implementing the suggestion! :D

**Comment by 06chaynes** [comment]
Also added a docs page for the cache modes to hopefully explain them a bit better
https://http-cache.rs/book/cache-modes.html
