### ISSUE TITLE
Can't use http-cache with un-cloneable requests

### ISSUE THREAD

**Issue by joolean** [06chaynes/http-cache#41]
When I use a client with this middleware installed to send _any_ request (even one using an "uncacheable" HTTP method such as PATCH) the middleware attempts to clone the request, which results in an error for uncloneable requests, such as those with a streaming body. For example:

```rust
           let patch_response_result = client
                .patch(upload_file_url.clone())
                .header("Content-Type", "application/offset+octet-stream")
                .header("Tus-Resumable", "1.0.0")
                .header("Upload-Offset", bytes_acknowledged)
                .body(Body::wrap_stream(strm))
                .send()
                .await;
```
yields: `Middleware error: Request object is not cloneable. Are you passing a streaming body?`

I believe the issue is here: https://github.com/06chaynes/http-cache/blob/main/http-cache-reqwest/src/lib.rs#L138 (gets called regardless of whether the request is cacheable)

**Comment by 06chaynes** [comment]
Thought about this a bit more and I could possibly add a new method that would be called in the middleware implementation before the run method call to determine if the request is cacheable or not, then maybe just continue the chain normally rather than calling the run method. This would at least allow those requests determined non cachable to proceed without needing to be cloned.

**Comment by 06chaynes** [comment]
@joolean not sure if you'd be interested in the details but I made a [branch to test this change](https://github.com/06chaynes/http-cache/tree/pre-flight-check). Still looking things over and testing but I think it should work for your purposes in its current state. If it's determined to be a cacheable request then the logic would still run and error if a clone isn't possible, but now if it's determined to not be a cacheable request it the client implementation should run without cloning the request.

**Comment by 06chaynes** [comment]
Just FYI I finished up these changes and merged this into develop, so it'll be in the next release. This still can't work with requests that can't be cloned and determined to be cacheable but now it should at least work in those situations where it's determined to not be cacheable. Hope this update helps out!

**Comment by joolean** [comment]
Thanks for working on this @06chaynes! This sounds like it'll address my use case quite well. I've been busy with work but will try out the new release as soon as it's ready.

**Comment by 06chaynes** [comment]
Sounds good! Just published the new versions so should be good to test whenever. Feel free to let me know if you have any issues!
