### ISSUE TITLE
Option not to add additional cache headers

### ISSUE THREAD

**Issue by eirnym** [06chaynes/http-cache#85]
In some cases I'd like to have transparent cache without adding `x-cache` and `x-cache-lookup` headers

**Comment by 06chaynes** [comment]
Thanks for your patience on this. I hope to have some time this weekend to make some updates and this one should be fairly simple to add.

**Comment by 06chaynes** [comment]
I merged this change into develop and it will be merged in with https://github.com/06chaynes/http-cache/pull/88

**Comment by 06chaynes** [comment]
crates have been published!
